kind: pipeline
name: default

steps:

- name: test_on_each_commit
  image: python
  commands:
  - pip install -r requirements-test.txt
  - pytest
  when:
    branch:
    - feature-*

- name: test-on-pullrequest-to-develop-and-master
  image: python
  commands:
  - pip install -r requirements-test.txt
  - pytest
  when:
    event:
    - pull_request
    branch:
    - develop
    - master

- name: test-on-merge-develop
  image: python
  commands:
  - pip install -r requirements-test.txt
  - pytest
  when:
    event:
    - merge
    branch:
    - develop

- name: build-and-publish-to-ecr-when-pr-dev  
  image: plugins/ecr
  settings:
    tags: "$DRONE_COMMIT"
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: 982989130295.dkr.ecr.us-east-1.amazonaws.com/datank/test-drone
    registry: 982989130295.dkr.ecr.us-east-1.amazonaws.com
  when:
    event:
    - pull_request
    branch:
    - develop

- name: notify-build-to-slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: alguno

