---
apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    "kops.k8s.io/instancegroup": hexapodo
  containers:
  - name: python
    image: 'python:3.7-alpine'
    tty: true
    command: 
    - cat
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: dind
    image: docker:18.05-dind
    tty: true
    command: 
    - cat
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
volumes:
  - name: dind-storage
    emptyDir: {}
---
