---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    "iam.amazonaws.com/role": "arn:aws:iam::982989130295:role/rolecillo.services.datanktzingo.datank.ai"
spec:
  nodeSelector:
    "kops.k8s.io/instancegroup": hexapodo
  containers:
  - name: python
    image: 'python:3.7-alpine'
    tty: true
    command: 
    - cat
---
